name: "Ops automation"
description: Ops automation actions'
author: "Pwei1018"
inputs:
  ZENHUB_TOKEN:
    description: "Zenhub API Token"
    required: true
  ZENHUB_REPO_ID:
    description: "Zenhub Repo Id"
    required: true
  GIT_TOKEN:
    description: "Github Access Token"
    required: true
  GIT_OWNER:
    description: "Github Repo Owner"
    required: true
  GIT_REPO:
    description: "Github Repo"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
